server:
  port:8080

spring:
  h2:
    console:
      enable: true
      path: /test_db

  datasource:
    url : jdbc:h2:mem:paydb;MODE=mysql;
    platform: h2
    username : hsb
    password : 1234
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true